import axios from 'axios'
import { supabase } from '../config/supabase'

const api = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:5000' })

api.interceptors.request.use(async (config) => {
  const { data } = await supabase.auth.getSession()
  if (data.session?.access_token) config.headers.Authorization = `Bearer ${data.session.access_token}`
  return config
})

export const getHealth = () => api.get('/api/health')
export const getAnalyticsOverview = () => api.get('/api/analytics/overview')
export const askAdvisor = (question) => api.post('/api/advisor/ask', { question })
export const getAgentActivity = () => api.get('/api/agents/activity')
export const getManagerContext = () => api.get('/api/manager/context')
export const requestManager = (message) => api.post('/api/manager/request', { message })
export const getManagerActions = () => api.get('/api/manager/actions')
export const confirmManagerAction = (actionId) => api.post(`/api/manager/actions/${actionId}/confirm`)
export const cancelManagerAction = (actionId) => api.post(`/api/manager/actions/${actionId}/cancel`)
export const getProducts = () => api.get('/api/products')
export const getStallAvailability = () => api.get('/api/stall-availability')
export const getVendorStallAvailability = () => api.get('/api/stall-availability/vendor')
export const updateStallOverride = (values) => api.patch('/api/stall-availability/override', values)
export const createProduct = (values) => api.post('/api/products', values)
export const suggestRecipeDraft = (values) => api.post('/api/products/recipe-draft', values)
export const createOrder = (order) => api.post('/api/orders', order)
export const getOrderTracking = (trackingToken) => api.get(`/api/orders/track/${trackingToken}`)
export const getOrders = () => api.get('/api/orders')
export const updateOrderStatus = (orderId, status) => api.patch(`/api/orders/${orderId}/status`, { status })
export const getInventory = () => api.get('/api/inventory')
export const updateInventory = (productId, values) => api.patch(`/api/inventory/${productId}`, values)
export const getMarketingSettings = () => api.get('/api/marketing/settings')
export const updateMarketingSettings = (values) => api.patch('/api/marketing/settings', values)
export const getMarketingProducts = () => api.get('/api/marketing/products')
export const getMarketingCampaigns = () => api.get('/api/marketing/campaigns')
export const generateMarketingCampaign = (values) => api.post('/api/marketing/campaigns/generate', values)
export const updateMarketingCampaign = (campaignId, values) => api.patch(`/api/marketing/campaigns/${campaignId}`, values)
export const approveMarketingCampaign = (campaignId) => api.post(`/api/marketing/campaigns/${campaignId}/status`, { status: 'approved' })
export const recordMarketingShare = (campaignId) => api.post(`/api/marketing/campaigns/${campaignId}/share-opened`)
export const getIngredients = () => api.get('/api/inventory/ingredients')
export const createIngredient = (values) => api.post('/api/inventory/ingredients', values)
export const updateIngredient = (ingredientId, values) => api.patch(`/api/inventory/ingredients/${ingredientId}`, values)
export const adjustIngredient = (ingredientId, values) => api.post(`/api/inventory/ingredients/${ingredientId}/adjust`, values)
export const getIngredientAvailability = () => api.get('/api/inventory/availability')
export const getRecipe = (productId) => api.get(`/api/inventory/recipes/${productId}`)
export const updateRecipe = (productId, values) => api.put(`/api/inventory/recipes/${productId}`, values)